#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

secret=$(ynh_string_random --length=32)
ynh_app_setting_set --key=secret --value=$secret

tz="$(cat /etc/timezone)"
ynh_app_setting_set --key=timezone --value=$tz

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p $install_dir
mkdir -p $data_dir/media

chmod -R 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
chown -R $app:www-data "$data_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="pretix.cfg" --destination="$install_dir/pretix.cfg"

chmod 600 "$install_dir/pretix.cfg"
chown "$app:$app" "$install_dir/pretix.cfg"

mkdir -p /var/log/$app
touch "/var/log/$app/$app.log"
touch "/var/log/$app/$app-backend.log"
touch "/var/log/$app/$app-broker.log"
chown -R "$app:www-data" "/var/log/$app"

multi_redis_db backend broker redis_db

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd $install_dir
    ynh_exec_as_app python3 -m venv $install_dir/venv
    source "$install_dir/venv/bin/activate"
    ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/pip install --upgrade pip setuptools wheel django-redis
    ynh_hide_warnings $install_dir/venv/bin/pip install pretix gunicorn
    ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/pip install --upgrade-strategy eager --upgrade "pretix[postgres,redis]"
    export PATH="$PATH:$nodejs_dir" 
    ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/python3 -m pretix migrate
    chown -R $app:www-data "$install_dir" 
    ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/python3 -m pretix rebuild
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}-backend" --template="pretix-backend.service"
ynh_config_add_systemd --service="${app}-broker" --template="pretix-broker.service"

yunohost service add "${app}-backend" --description="Pretix backend" --log="/var/log/$app/$app-backend.log"
yunohost service add "${app}-broker" --description="Pretix broker" --log="/var/log/$app/$app-broker.log"

#=================================================
# ADD A CRON JOB
#=================================================

ynh_config_add --template="pretix.cron" --destination="/etc/cron.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="${app}-web" --action="start" --log_path="systemd"
ynh_systemctl --service="${app}-worker" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
