#!/bin/bash


#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping $app's systemd service..." --weight=1

ynh_systemd_action --service_name="$app" --action="stop" --log_path="systemd"
ynh_systemd_action --service_name="pretix-worker" --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

mkdir -p $install_dir

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SPECIFIC SETUP
#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing Python dependencies..." --weight=4

pushd $install_dir
	python3 -m venv $install_dir/venv
	source $install_dir/venv/bin/activate
	pip install --upgrade pip
	ynh_exec_warn_less pip install -U --upgrade-strategy eager pretix gunicorn
	ynh_exec_warn_less pip install pretix gunicorn
	python3 -m pretix migrate
	python3 -m pretix rebuild
	python3 -m pretix updateassets
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating $app's configuration files..." --weight=1

ynh_add_config --template="pretix.cfg" --destination="$install_dir/pretix.cfg"

chmod 600 "$install_dir/pretix.cfg"
chown "$app:$app" "$install_dir/pretix.cfg"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

ynh_add_nginx_config

ynh_add_systemd_config

yunohost service add "$app" --description="Ticket shop application" --log="/var/log/$app/$app.log"
yunohost service add "pretix-worker" --description="Pretix worker" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..." --weight=1

ynh_systemd_action --service_name="$app" --action="start" --log_path="systemd"
ynh_systemd_action --service_name="pretix-worker" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
